language: csharp
solution: ./Unit4.sln
install:
  - nuget restore ./Unit4.sln
script:
  - msbuild /p:Configuration=Debug ./Unit4.sln
  - mono ./packages/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./Unit4.Automation.Tests/bin/Debug/Unit4.Automation.Tests.dll --where="cat != RequiresExcelInstall"
  - mono ./packages/WiX.3.11.1/tools/candle.exe ./unit4-automation.wxs
  - WINEARCH=win32 winecfg
  - winetricks -q dotnet40
  - wine ./packages/WiX.3.11.1/tools/light.exe -sval ./unit4-automation.wixobj -sice:ICE91
addons:
  apt:
    packages:
      wine
      winetricks